services:

  llm-app:
    build: .
    container_name: llm-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chatdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - project

networks:
  project:
    external: true

#  docker compose exec db sh
#  psql -U postgres
#  CREATE DATABASE chatdb OWNER postgres;
#  CREATE TABLE posts (
#  id SERIAL PRIMARY KEY,
#  field1 VARCHAR(20) NOT NULL,
#  field2 VARCHAR(20) NOT NULL,
#  field3 VARCHAR(20) NOT NULL,
#  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
#  );